/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_RpmVersionComparator */

#ifndef _Included_org_example_RpmVersionComparator
#define _Included_org_example_RpmVersionComparator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_RpmVersionComparator
 * Method:    compareVersions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_RpmVersionComparator_compareVersions
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
